### ISSUE TITLE
Iterative Training Scripts

### ISSUE THREAD

**Issue by S1s-Z** [SkyworkAI/LLMs-as-Instructors#1]
Great and solid work! May I ask if you plan to make the iterative training scripts public? Because this will allow a better reproduction of your results on mistral. Thanks!

**Comment by yingjiahao14** [comment]
Thanks for you question. so the iterative training process is just to do evaluation, generation and training process iteratively: 
1. First get the new evaluation result from the target dataset.
2. Using  Strategy "Learning from Errors by Contrast"/ "Learning from Errors" to generate new training samples.
3. Using the training samples to train the model.
